# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-19 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20180219_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offersnippet',
            old_name='text',
            new_name='description',
        ),
    ]
