# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-19 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20180219_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='slogan',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
